variables:
  - group: PRG-dev-automation
  - name: analysisProject
    value: sample-omf-temperature_sensor-python-omf-20

trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: ArchitectureRepo
      type: git
      name: Architecture/Architecture
      ref: refs/heads/main
    - repository: templates
      type: github
      name: AVEVA/pipelines-templates
      endpoint: AVEVA
    - repository: antiMalwareTemplate
      name: Architecture/Architecture 
      ref: refs/heads/antiMalwareVersions/0.1
      type: git

jobs:
# --- ADDING TESTS JOB ---

  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: Cloud Platform CONNECT v2 Development
    steps:
      - task: DownloadSecureFile@1
        name: downloadAppSettings
        displayName: 'Download secure appsettings'
        inputs:
          secureFile: 'PRG-CONNECT_Prod_AVEVA-Lighthouse-OMF.appsettings.json'

      - pwsh: |
          $source = "$(downloadAppSettings.secureFilePath)"
          $destination = Join-Path "$(Build.SourcesDirectory)" "appsettings.json"
          Copy-Item -Path $source -Destination $destination -Force
          Write-Host "Placed appsettings.json next to program.py"
        displayName: 'Place appsettings.json'

      - script: |
          echo Install test tools   
          pip install pytest
          echo Install requirements
          pip install -r requirements.txt
          echo Run tests
          python -m pytest --junitxml=junit/test-results.xml ./test.py
          echo Complete
        displayName: 'Run tests'
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          failTaskOnFailedTests: true
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()

    # --- END TESTS JOB ---

  - template: '/code-analysis/code-analysis.yml@templates'
    parameters:
      poolForExecution: Cloud Platform CONNECT v2 Development
      useRequirementsTxt: true
      buildSteps:
        - script: |
            echo "Installing Python dependencies"
            python -c "import sys; print(sys.executable)"
            python -m pip --version
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
            python -m pip freeze
          displayName: 'Install Python dependencies'